name: project

services:
  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  phoenix:
    image: ${DOCKER_IMAGE:-time-manager:backend}
    build: backend/project
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ecto://${PGUSER}:${PGPASSWORD}@db:5432/${PGDATABASE}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?SECRET_KEY_BASE is required}
      PHX_HOST: ${PHX_HOST:-localhost}
      PHX_SERVER: "true"
    depends_on:
      - db

  frontend:
    image: ${FRONTEND_DOCKER_IMAGE:-time-manager:frontend}
    build: frontend/project
    ports:
      - "80:80"
    depends_on:
      - phoenix

volumes:
  db_data:
